CREATE OR REPLACE TRIGGER count
BEFORE INSERT ON CLIENT
FOR EACH ROW
DECLARE
  RowCount NUMBER;
BEGIN
  SELECT COUNT(*) INTO RowCount FROM CLIENT;
  DBMS_OUTPUT.PUT_LINE('The table has ' || RowCount || ' rows.');
END;
